create table if not exists map_place_image_tb (
    id bigint generated by default as identity primary key,
    normalized_name varchar(200) not null unique,
    place_name varchar(200) not null,
    image_url varchar(2000) not null,
    source varchar(50) not null,
    created_at timestamp not null default current_timestamp
);

merge into map_place_image_tb (normalized_name, place_name, image_url, source, created_at) key (normalized_name) values
('감천문화마을', '감천문화마을', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Gamcheon_Culture_Village.jpg', 'SEED', current_timestamp),
('파라다이스호텔부산', '파라다이스호텔부산', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', 'SEED', current_timestamp),
('시그니엘부산', '시그니엘부산', 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80', 'SEED', current_timestamp),
('해운대해수욕장', '해운대해수욕장', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Haeundae_Beach_Busan.jpg', 'SEED', current_timestamp),
('광안리해수욕장', '광안리해수욕장', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Gwangan_Bridge_2015.jpg', 'SEED', current_timestamp),
('부산타워', '부산타워', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Busan_Tower_at_Yongdusan_Park.jpg', 'SEED', current_timestamp),
('송도해상케이블카', '송도해상케이블카', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Songdo_Beach%2C_Busan.jpg', 'SEED', current_timestamp),
('태종대', '태종대', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Taejongdae_Resort_Park_Busan.jpg', 'SEED', current_timestamp),
('부산시민공원', '부산시민공원', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Busan_Citizen_Park.jpg', 'SEED', current_timestamp),
('아쿠아리움', '씨라이프부산아쿠아리움', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Aquarium_tunnel.jpg', 'SEED', current_timestamp),
('국립해양박물관', '국립해양박물관', 'https://upload.wikimedia.org/wikipedia/commons/8/85/National_Maritime_Museum_of_Korea.jpg', 'SEED', current_timestamp),
('롯데월드어드벤처부산', '롯데월드어드벤처부산', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Theme_park_roller_coaster.jpg', 'SEED', current_timestamp),
('경복궁', '경복궁', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Gyeongbokgung-Geunjeongjeon.jpg', 'SEED', current_timestamp),
('북촌한옥마을', '북촌한옥마을', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Bukchon_Hanok_Village.jpg', 'SEED', current_timestamp),
('인사동거리', '인사동거리', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Insadong_Gil.jpg', 'SEED', current_timestamp),
('창덕궁', '창덕궁', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Changdeokgung_Injeongjeon.jpg', 'SEED', current_timestamp);


create table if not exists lodging_tb (
    id bigint generated by default as identity primary key,
    external_place_id varchar(64) not null unique,
    name varchar(200) not null,
    normalized_name varchar(200) not null,
    category_group_code varchar(10) not null,
    category_name varchar(300),
    phone varchar(50),
    address varchar(300),
    road_address varchar(300),
    region_key varchar(50) not null,
    lat decimal(10, 7) not null,
    lng decimal(10, 7) not null,
    place_url varchar(500),
    room_price int not null default 0,
    fee int not null default 0,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);
