-- H2 map-related cache and lodging seed data for map-detail page

create table if not exists map_place_image_tb (
    id bigint generated by default as identity primary key,
    normalized_name varchar(200) not null unique,
    place_name varchar(200) not null,
    image_url varchar(2000) not null,
    source varchar(50) not null,
    created_at timestamp not null default current_timestamp
);

merge into map_place_image_tb (normalized_name, place_name, image_url, source, created_at)
key (normalized_name)
values
('감천문화마을', '감천문화마을', 'https://upload.wikimedia.org/wikipedia/commons/7/70/Gamcheon_Culture_Village.jpg', 'SEED', current_timestamp),
('파라다이스호텔부산', '파라다이스 호텔 부산', 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', 'SEED', current_timestamp),
('시그니엘부산', '시그니엘 부산', 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80', 'SEED', current_timestamp),
('해운대해수욕장', '해운대해수욕장', 'https://upload.wikimedia.org/wikipedia/commons/a/a8/Haeundae_Beach_Busan.jpg', 'SEED', current_timestamp),
('광안리해수욕장', '광안리해수욕장', 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Gwangan_Bridge_2015.jpg', 'SEED', current_timestamp),
('부산타워', '부산타워', 'https://upload.wikimedia.org/wikipedia/commons/2/27/Busan_Tower_at_Yongdusan_Park.jpg', 'SEED', current_timestamp),
('송도해상케이블카', '송도해상케이블카', 'https://upload.wikimedia.org/wikipedia/commons/0/05/Songdo_Beach%2C_Busan.jpg', 'SEED', current_timestamp),
('태종대', '태종대', 'https://upload.wikimedia.org/wikipedia/commons/3/33/Taejongdae_Resort_Park_Busan.jpg', 'SEED', current_timestamp),
('부산시민공원', '부산시민공원', 'https://upload.wikimedia.org/wikipedia/commons/7/75/Busan_Citizen_Park.jpg', 'SEED', current_timestamp),
('씨라이프부산아쿠아리움', '씨라이프 부산 아쿠아리움', 'https://upload.wikimedia.org/wikipedia/commons/4/49/Aquarium_tunnel.jpg', 'SEED', current_timestamp),
('국립해양박물관', '국립해양박물관', 'https://upload.wikimedia.org/wikipedia/commons/8/85/National_Maritime_Museum_of_Korea.jpg', 'SEED', current_timestamp),
('롯데월드어드벤처부산', '롯데월드 어드벤처 부산', 'https://upload.wikimedia.org/wikipedia/commons/f/f9/Theme_park_roller_coaster.jpg', 'SEED', current_timestamp),
('경복궁', '경복궁', 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Gyeongbokgung-Geunjeongjeon.jpg', 'SEED', current_timestamp),
('북촌한옥마을', '북촌한옥마을', 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Bukchon_Hanok_Village.jpg', 'SEED', current_timestamp),
('인사동거리', '인사동 거리', 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Insadong_Gil.jpg', 'SEED', current_timestamp),
('창덕궁', '창덕궁', 'https://upload.wikimedia.org/wikipedia/commons/c/cd/Changdeokgung_Injeongjeon.jpg', 'SEED', current_timestamp);

create table if not exists lodging_tb (
    id bigint generated by default as identity primary key,
    external_place_id varchar(64) not null unique,
    name varchar(200) not null,
    normalized_name varchar(200) not null,
    category_group_code varchar(10) not null,
    category_name varchar(300),
    phone varchar(50),
    address varchar(300),
    road_address varchar(300),
    region_key varchar(50) not null,
    lat decimal(10, 7) not null,
    lng decimal(10, 7) not null,
    place_url varchar(500),
    room_price int not null default 0,
    fee int not null default 0,
    is_active boolean not null default true,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp
);

create index if not exists idx_lodging_region_active on lodging_tb (region_key, is_active);
create index if not exists idx_lodging_geo on lodging_tb (lat, lng);
create index if not exists idx_lodging_name on lodging_tb (normalized_name);

merge into lodging_tb (
    external_place_id,
    name,
    normalized_name,
    category_group_code,
    category_name,
    phone,
    address,
    road_address,
    region_key,
    lat,
    lng,
    place_url,
    room_price,
    fee,
    is_active,
    created_at,
    updated_at
)
key (external_place_id)
values
('kakao_10001', '파라다이스 호텔 부산', '파라다이스호텔부산', 'AD5', '숙박 > 호텔', '051-000-0001', '부산광역시 해운대구', '부산광역시 해운대구 해운대해변로 296', 'busan', 35.1586970, 129.1603840, 'https://place.map.kakao.com/10001', 392500, 70650, true, current_timestamp, current_timestamp),
('kakao_10002', '시그니엘 부산', '시그니엘부산', 'AD5', '숙박 > 호텔', '051-000-0002', '부산광역시 해운대구', '부산광역시 해운대구 달맞이길 30', 'busan', 35.1587600, 129.1667410, 'https://place.map.kakao.com/10002', 397450, 71541, true, current_timestamp, current_timestamp),
('kakao_20001', '서울 롯데 호텔', '서울롯데호텔', 'AD5', '숙박 > 호텔', '02-000-0001', '서울특별시 중구', '서울특별시 중구 을지로 30', 'seoul', 37.5651000, 126.9810000, 'https://place.map.kakao.com/20001', 350000, 63000, true, current_timestamp, current_timestamp),
('kakao_30001', '제주 오션뷰 호텔', '제주오션뷰호텔', 'AD5', '숙박 > 호텔', '064-000-0001', '제주특별자치도 제주시', '제주특별자치도 제주시 애월해안로 100', 'jeju', 33.4627000, 126.3094000, 'https://place.map.kakao.com/30001', 280000, 50400, true, current_timestamp, current_timestamp),
('kakao_40001', '경주 라한 셀렉트', '경주라한셀렉트', 'AD5', '숙박 > 호텔', '054-000-0001', '경상북도 경주시', '경상북도 경주시 보문로 338', 'gyeongju', 35.8382000, 129.2827000, 'https://place.map.kakao.com/40001', 240000, 43200, true, current_timestamp, current_timestamp),
('kakao_50001', '강릉 씨사이드 호텔', '강릉씨사이드호텔', 'AD5', '숙박 > 호텔', '033-000-0001', '강원특별자치도 강릉시', '강원특별자치도 강릉시 창해로 307', 'gangwon', 37.7797000, 128.9435000, 'https://place.map.kakao.com/50001', 210000, 37800, true, current_timestamp, current_timestamp);
