{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-aspectj",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aspectj-4.0.3.jar",
          "url": "spring-boot-starter-aspectj-4.0.3.jar",
          "size": 4765,
          "sha512": "242d8540cc7dd0b3ea15690247871e83216e6488b142b1e1a94bfc0a950c04aab42859302e8d3fcc5a903d7c5e99cba33d5764b350c34092e40ed573fe59f1f0",
          "sha256": "2371dfff2bab683167d9d62ab64a824907ac071b3a1f51dd97997de30a479851",
          "sha1": "1bb8dc73680f22d6953974d90cef1284b08cf9eb",
          "md5": "88bebacbe4f9645382c28b62f7b5729f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.5"
          }
        },
        {
          "group": "org.aspectj",
          "module": "aspectjweaver",
          "version": {
            "requires": "1.9.25.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-aspectj-4.0.3.jar",
          "url": "spring-boot-starter-aspectj-4.0.3.jar",
          "size": 4765,
          "sha512": "242d8540cc7dd0b3ea15690247871e83216e6488b142b1e1a94bfc0a950c04aab42859302e8d3fcc5a903d7c5e99cba33d5764b350c34092e40ed573fe59f1f0",
          "sha256": "2371dfff2bab683167d9d62ab64a824907ac071b3a1f51dd97997de30a479851",
          "sha1": "1bb8dc73680f22d6953974d90cef1284b08cf9eb",
          "md5": "88bebacbe4f9645382c28b62f7b5729f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aspectj-4.0.3-javadoc.jar",
          "url": "spring-boot-starter-aspectj-4.0.3-javadoc.jar",
          "size": 4765,
          "sha512": "242d8540cc7dd0b3ea15690247871e83216e6488b142b1e1a94bfc0a950c04aab42859302e8d3fcc5a903d7c5e99cba33d5764b350c34092e40ed573fe59f1f0",
          "sha256": "2371dfff2bab683167d9d62ab64a824907ac071b3a1f51dd97997de30a479851",
          "sha1": "1bb8dc73680f22d6953974d90cef1284b08cf9eb",
          "md5": "88bebacbe4f9645382c28b62f7b5729f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-aspectj-4.0.3-sources.jar",
          "url": "spring-boot-starter-aspectj-4.0.3-sources.jar",
          "size": 4765,
          "sha512": "242d8540cc7dd0b3ea15690247871e83216e6488b142b1e1a94bfc0a950c04aab42859302e8d3fcc5a903d7c5e99cba33d5764b350c34092e40ed573fe59f1f0",
          "sha256": "2371dfff2bab683167d9d62ab64a824907ac071b3a1f51dd97997de30a479851",
          "sha1": "1bb8dc73680f22d6953974d90cef1284b08cf9eb",
          "md5": "88bebacbe4f9645382c28b62f7b5729f"
        }
      ]
    }
  ]
}
