{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-h2console",
    "version": "4.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.4.240"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-h2console-4.0.3.jar",
          "url": "spring-boot-h2console-4.0.3.jar",
          "size": 13929,
          "sha512": "4690bb62dc434bef94f4058e26f017f4b6ffb35d7a81e4bb2929b29c7397c1c9cd660bc37c3af37a738cdd1840bed56ba795263e56b59a22fb2737b0a1958702",
          "sha256": "ceeae201c5175d4adc61cabc8db6eb9dfe9aedef2d8b761a61ab081f22b93dbb",
          "sha1": "9fe4d9d0b88858d6fc1373dfce62f36cd2376cf4",
          "md5": "18097a8082412073331dab9b3f74276b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "4.0.3"
          }
        },
        {
          "group": "jakarta.servlet",
          "module": "jakarta.servlet-api",
          "version": {
            "requires": "6.1.0"
          }
        },
        {
          "group": "com.h2database",
          "module": "h2",
          "version": {
            "requires": "2.4.240"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-h2console-4.0.3.jar",
          "url": "spring-boot-h2console-4.0.3.jar",
          "size": 13929,
          "sha512": "4690bb62dc434bef94f4058e26f017f4b6ffb35d7a81e4bb2929b29c7397c1c9cd660bc37c3af37a738cdd1840bed56ba795263e56b59a22fb2737b0a1958702",
          "sha256": "ceeae201c5175d4adc61cabc8db6eb9dfe9aedef2d8b761a61ab081f22b93dbb",
          "sha1": "9fe4d9d0b88858d6fc1373dfce62f36cd2376cf4",
          "md5": "18097a8082412073331dab9b3f74276b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-h2console-4.0.3-javadoc.jar",
          "url": "spring-boot-h2console-4.0.3-javadoc.jar",
          "size": 112747,
          "sha512": "c86e9543a59405c7cc363c9acee8cd339c4bfb6a1fc9ea9064954fd44f9e0289b315f4947bcd35e6efba3c067a3e3f1db30614b763ad2b9d41f0ec1da12b94be",
          "sha256": "88460876a01c7988819464b5ea93262b90df280b5dff1ea0096bb344240c6e65",
          "sha1": "9475a2efddc4fe4bc03cf833c6ed8db964e8ed8c",
          "md5": "34245673ad6e8601255227c602a9559d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-h2console-4.0.3-sources.jar",
          "url": "spring-boot-h2console-4.0.3-sources.jar",
          "size": 9812,
          "sha512": "309b35a675df2d0048580f80b5980fc48647f45c99a409f26b19f5fbb7486ce061b5c3c104ec96ec5b90f12cebef04cbc0d996ab3909ab68b1164049f715f73b",
          "sha256": "2c2d5189e22310f3ece5cc9d30c6935c11fcd0673f8c2ed130b1f121e2405c00",
          "sha1": "71441691c13d61e2996e4b33f2817081d59c5b3b",
          "md5": "739d8416c1ff1e090d91113300f822a8"
        }
      ]
    }
  ]
}
